#pragma once

#ifndef KEY_ESCAPE
#define KEY_ESCAPE	27
#endif

#define META_KEY_FLAG	0x80

/* Key context is the place where the user presses a key. A key can have
 * different meanings in different places. */
enum key_context
{
	CON_MENU  = 0,
	CON_PANEL = 1,
	CON_ENTRY = 2
};

enum key_cmd
{
	KEY_CMD_QUIT_CLIENT,
	KEY_CMD_GO,

	KEY_CMD_MENU_DOWN,
	KEY_CMD_MENU_UP,
	KEY_CMD_MENU_LEFT,
	KEY_CMD_MENU_RIGHT,
	KEY_CMD_MENU_NPAGE,
	KEY_CMD_MENU_PPAGE,
	KEY_CMD_MENU_FIRST,
	KEY_CMD_MENU_LAST,
	KEY_CMD_MENU_EXTEND_DOWN,
	KEY_CMD_MENU_EXTEND_UP,
	KEY_CMD_MENU_EXEC,
	KEY_CMD_MENU_EXEC_NOCLOSE,
	KEY_CMD_QUIT,
	KEY_CMD_STOP,
	KEY_CMD_NEXT,
	KEY_CMD_PREVIOUS,
	KEY_CMD_PAUSE,
	KEY_CMD_TOGGLE_READ_TAGS,
	KEY_CMD_TOGGLE_REPEAT,
	KEY_CMD_TOGGLE_AUTO_NEXT,
	KEY_CMD_TOGGLE_MENU,
	KEY_CMD_TOGGLE_LAYOUT,
	KEY_CMD_PLIST_ADD,
	KEY_CMD_PLIST_INS,
	KEY_CMD_PLIST_CLEAR,
	KEY_CMD_PLIST_REMOVE_DEAD_ENTRIES,
	KEY_CMD_MIXER_DEC_1,
	KEY_CMD_MIXER_INC_1,
	KEY_CMD_MIXER_DEC_5,
	KEY_CMD_MIXER_INC_5,
	KEY_CMD_SEEK_FORWARD,
	KEY_CMD_SEEK_BACKWARD,
	KEY_CMD_SEEK_FORWARD_5,
	KEY_CMD_SEEK_BACKWARD_5,
	KEY_CMD_HIDE_MESSAGE,
	KEY_CMD_REFRESH,
	KEY_CMD_RELOAD,
	KEY_CMD_TOGGLE_SHOW_HIDDEN_FILES,
	KEY_CMD_GO_MUSIC_DIR,
	KEY_CMD_PLIST_DEL,
	KEY_CMD_MENU_SEARCH,
	KEY_CMD_PLIST_SAVE,
	KEY_CMD_GO_TO_PLAYING_FILE,
	KEY_CMD_GO_DIR,
	KEY_CMD_GO_DIR_UP,
	KEY_CMD_TOGGLE_SHUFFLE,
	KEY_CMD_CANCEL,
	KEY_CMD_GO_URL,
	KEY_CMD_VOLUME_10,
	KEY_CMD_VOLUME_20,
	KEY_CMD_VOLUME_30,
	KEY_CMD_VOLUME_40,
	KEY_CMD_VOLUME_50,
	KEY_CMD_VOLUME_60,
	KEY_CMD_VOLUME_70,
	KEY_CMD_VOLUME_80,
	KEY_CMD_VOLUME_90,
	KEY_CMD_TOGGLE_MIXER,
	KEY_CMD_HISTORY_UP,
	KEY_CMD_HISTORY_DOWN,
	KEY_CMD_DELETE_START,
	KEY_CMD_DELETE_END,
	KEY_CMD_PLIST_MOVE_UP,
	KEY_CMD_PLIST_MOVE_DOWN,
	KEY_CMD_ADD_STREAM,
	KEY_CMD_TOGGLE_PLAYLIST_FULL_PATHS,
	KEY_CMD_TOGGLE_SOFTMIXER,
	KEY_CMD_TOGGLE_EQUALIZER,
	KEY_CMD_EQUALIZER_REFRESH,
	KEY_CMD_EQUALIZER_PREV,
	KEY_CMD_EQUALIZER_NEXT,
	KEY_CMD_TOGGLE_MAKE_MONO,
	KEY_CMD_RATE_0,
	KEY_CMD_RATE_1,
	KEY_CMD_RATE_2,
	KEY_CMD_RATE_3,
	KEY_CMD_RATE_4,
	KEY_CMD_RATE_5,
	KEY_CMD_SEEK_0,
	KEY_CMD_SEEK_1,
	KEY_CMD_SEEK_2,
	KEY_CMD_SEEK_3,
	KEY_CMD_SEEK_4,
	KEY_CMD_SEEK_5,
	KEY_CMD_SEEK_6,
	KEY_CMD_SEEK_7,
	KEY_CMD_SEEK_8,
	KEY_CMD_SEEK_9,
	KEY_CMD_MENU,

	KEY_CMD_TAG_ARTIST,
	KEY_CMD_TAG_ALBUM,
	KEY_CMD_TAG_TITLE,
	KEY_CMD_WRITE_TAGS,
	KEY_CMD_TAG_ADD_NUMBERS,
	KEY_CMD_TAG_DEL_NUMBERS,

	KEY_CMD_FILES_MV,
	KEY_CMD_FILES_RM,

	KEY_CMD_WRONG
};

void    keys_init();
key_cmd get_key_cmd(key_context context, wchar_t c, int f); // c: regular key, f: Fkey, arrow, ...
str     hotkey(key_cmd cmd); // for display in menu items
