.\" Start example.
.de EX
.  nr mE \\n(.f
.  nf
.  nh
.  ft CW
..
.
.\" End example.
.de EE
.  ft \\n(mE
.  fi
.  hy \\n(HY
..
.
.TH AMOC 1 "11 January 2020" "Version 2.6-alpha3" "Music On Console"
.ad l
.SH NAME
AMOC \- Console audio player
.LP
.SH SYNOPSIS
\fBamoc\fR [\fIOPTIONS\fR] [\fIFILE\fR|\fIDIR\fR ...]
.LP
.SH DESCRIPTION
AMOC is a console audio player with simple ncurses interface.  It supports
OGG, WAV, MP3 and other formats.  Just run \fBamoc\fP, go to some directory
using the menu and press enter to start playing the file.  The program will
automatically play the rest of the files in the directory.
.LP
With no options and no file arguments the program begins in current
directory, or in \fBMusicDir\fP if the \fBStartInMusicDir\fP option is set
in the configuration file.  If you give a directory on the command line,
AMOC will try to go there.  If a playlist is given, then it is loaded.
With multiple files, playlists or directories, everything will be added to
the playlist recursively (including the contents of any playlist given).
(Note that relative paths in playlists are resolved with respect to the
directory of the playlist, or of the symlink being used to reference it.)
.LP
.SH OPTIONS
If an option can also be set in the configuration file the command line
overrides it (but see the \fB\-O\fP option for the list-valued
configuration options exception).
.LP
.TP
\fB\-D\fP, \fB\-\-debug\fP
Run AMOC in debug mode.  The client and server log a lot of information
to debug files.  Don't use this; the server log is large.  This is only
available if AMOC was compiled without \fB\-\-disable\-debug\fP.
.LP
.TP
\fB\-S\fP, \fB\-\-server\fP
Run only the server and exit.
.LP
.TP
\fB\-F\fP, \fB\-\-foreground\fP
Implies \fB\-S\fP.  Run the server in foreground and log everything to stdout.
.LP
.TP
\fB\-p\fP, \fB\-\-play\fP
Start playing from the first item on the playlist.
.LP
.TP
\fB\-l\fP, \fB\-\-playit\fP
Play files given on the command line without modifying the clients'
playlists.
.LP
.TP
\fB\-f\fP, \fB\-\-next\fP
Request playing the next song from the server's playlist.
.LP
.TP
\fB\-r\fP, \fB\-\-previous\fP
Request playing the previous song from the server's playlist.
.LP
.TP
\fB\-s\fP, \fB\-\-stop\fP
Request the server to stop playing.
.LP
.TP
\fB\-x\fP, \fB\-\-exit\fP
Bring down the server.
.LP
.TP
\fB\-P\fP, \fB\-\-pause\fP
Request the server to pause playing.
.LP
.TP
\fB\-U\fP, \fB\-\-unpause\fP
Request the server to resume playing when paused.
.LP
.TP
\fB\-G\fP, \fB\-\-toggle\-pause\fP
Toggle between play and pause.
.LP
.TP
\fB\-k\fP [\fB+\fP|\fB\-\fP]\fIN\fP, \
\fB\-\-seek \fP[\fB+\fP|\fB\-\fP]\fIN\fP
Seek forward (positive) or backward (negative) by \fIN\fP seconds in the
file currently being played.
.LP
.TP
\fB\-A\fP, \fB\-\-ascii\fP
Use ASCII characters to draw lines.  (This helps on some terminals.)
.LP
.TP
\fB\-h\fP, \fB\-\-help\fP
Print a list of options with short descriptions and exit.
.LP
.TP
\fB\-\-usage\fP
Print a synopsis of the amoc command and exit.
.LP
.TP
\fB\-V\fP, \fB\-\-version\fP
Print the program version and exit.
.LP
.TP
\fB\-v\fP [\fB+\fP|\fB\-\fP]\fIN\fP, \
\fB\-\-volume\fP [\fB+\fP|\fB\-\fP]\fIN\fP
Adjust the mixer volume.  You can set (\fB\-v 50\fP) or adjust
(\fB\-v +10\fP, \fB\-v \-10\fP).
.LP
.TP
\fB\-j\fP \fIN\fP{\fBs\fP|\fB%\fP}, \fB\-\-jump\fP \fIN\fP{\fBs\fP|\fB%\fP}
Jump to some position in the current file.  \fIN\fP is the number of seconds
(when followed by an '\fBs\fP') or the percent of total file time (when
followed by a '\fB%\fP').
.LP
.RS
.EX
Examples: \fB\-j 10s\fP, \fB\-j 50%\fP
.EE
.RE
.LP
.SH ENVIRONMENT VARIABLES
The following environment variables are used directly by AMOC.  Additional
variables may be relevant to the libraries AMOC uses.  Also, any environment
variable may be accessed from the configuration file.
.LP
.TP
.B ESCDELAY
An ncurses(3X) variable which specifies the delay (in milliseconds)
after which it will treat an ESC as a standalone key and not part of
an escaped character sequence (such as is generated by function keys).
AMOC sets this value to 25ms by default, which is sufficient for most
systems.
.LP
.TP
.B HOME
Tells AMOC where your home directory is located and is used for various
purposes, including the default location of the AMOC directory.
.LP
.TP
.B TERM \fPand\fB WINDOW
Used by AMOC to distinguish between X-terminals, screen(1) and console
terminals.  AMOC uses the configuration options \fBXTerms\fP and
\fBScreenTerms\fP to help make this determination.
.LP
.SH FILES
.TP
.B ~/.config/amoc or ~/.amoc
Directory for the configuration file, socket, the pid file and other data.
.LP
.TP
.B ~/.config/amoc/config or ~/.amoc/config
Configuration file for AMOC.  The format is very simple; to see how to use
it look at the example configuration file (\fBconfig.example\fP) distributed
with the program.  The example file fully describes all the configuration
options, and so is a useful reference when using the \fB\-O\fP option.  As
this file can specify commands which invoke other applications AMOC will
refuse to start if it is not owned by either root or the current user, or if
it is writable by anyone other than its owner.
.LP
.TP
.B ~/.popt
.TQ
.B /etc/popt
The default files POPT reads to obtain aliased options.  As these files can
specify commands which invoke other applications, AMOC will refuse to start
if it is not owned by root or the current user, or if it is writable by
anyone other than its owner.
.LP
.TP
.B ~/.amoc/colors
Theme file.
.LP
.TP
.B ~/.amoc/keymap
Keymap file.
.LP
.TP
.B amoc_client_log
.TQ
.B amoc_server_log
Client and server log files.  These files are created in the directory in
which the client and server are started.  (Also see the \fB\-D\fP option.)
.LP
.SH BUGS
Command line options that affect the server behaviour (like
\fB\-\-sound\-driver\fP) are ignored if the server is already running at
the time of executing \fBamoc\fP.  The user is not warned about this.
.LP
.SH HOMEPAGE
http://github.com/hilgenberg/moc/
.br
http://moc.daper.net/
.LP
.SH AUTHOR
Damian Pietras     <daper@daper.net>
.br
MOC Maintainer(s)  <mocmaint@daper.net>
